CREATE TABLE IF NOT EXISTS partners (
  id SERIAL PRIMARY KEY,
  partner_id VARCHAR(50) UNIQUE NOT NULL,
  partner_name VARCHAR(255) NOT NULL,
  status VARCHAR(50) NOT NULL,
  requested_products JSONB DEFAULT '[]',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);